export const COMMIT_MESSAGE = 'COMMIT_MESSAGE'
export const DELETE_LAST_MESSAGE = 'DELETE_LAST_MESSAGE'
export const THINKING_MESSAGE = 'THINKING_MESSAGE'
export const REGISTER_EXTERNAL_MESSAGE = 'REGISTER_EXTERNAL_MESSAGE'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'

export const INIT = 'INIT'
export const UPDATE_INITIAL_STATE = 'UPDATE_INITIAL_STATE'

export const SET_NICKNAME = 'SET_NICKNAME'
export const SET_BUDDY_NICKNAME = 'SET_BUDDY_NICKNAME'
