export const COMMIT_MESSAGE = 'COMMIT_MESSAGE'
export const DELETE_LAST_MESSAGE = 'DELETE_LAST_MESSAGE'
export const THINKING_MESSAGE = 'THINKING_MESSAGE'
export const REGISTER_EXTERNAL_MESSAGE = 'REGISTER_EXTERNAL_MESSAGE' 
